# SPDX-License-Identifier: Apache-2.0
[Content]
RemoveFiles=
        /usr/include
        /usr/share/OVMF
        /usr/share/ovmf
        /usr/share/doc
        /usr/share/info
        /usr/share/locale
        /usr/share/man
        /usr/**/*.a
        /usr/**/*.la
        /var/cache/debconf
        /var/lib/dbus/machine-id
        /var/lib/dpkg
        /var/lib/ucf
        /var/log/*

[Build]
Environment=DSTACK_BUILD_FLAVOR=prod
