#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0
"""sca — self-contained dstack app builder.

build a dstack `app-compose.json` whose application is embedded directly inside
it (base64), with NO docker and NO registry pull. at boot the measured
`bash_script` decodes the embedded files into a tmpfs runtime dir and runs the
app under a systemd service (Restart=always), so systemd supervises it the way
docker would.

why this is secure: the whole app-compose.json (including the embedded payloads)
is hashed into the compose-hash and extended to RTMR3, so the exact bytes you
ship are covered by remote attestation and gated by the on-chain whitelist.

subcommands:
  new <dir>     scaffold a project (sca.toml + README + dist/)
  build         read sca.toml and emit app-compose.json

constraints baked in from the dstack guest runtime (verified on a live CVM):
  - guest userland is busybox and has NO `base64`; decoding uses `openssl`.
  - `/run`, `/tmp`, `/dev/shm` are tmpfs and mounted exec (no noexec).
  - init is systemd; `systemctl` / `systemd-run` are available.
  - cwd of the script is /dstack, where `app-compose.json` is symlinked.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path

# the guest copies app-compose.json into the CVM with this hard cap
# (dstack-util HostShared::copy). base64 inflates payloads ~33%.
APP_COMPOSE_MAX_BYTES = 50 * 1024 * 1024

DEFAULT_ENV_FILE = "/dstack/.host-shared/.decrypted-env"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def die(msg: str) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def slugify(name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_.-]+", "-", name.strip()).strip("-")
    return slug or "app"


def human(n: int) -> str:
    f = float(n)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if f < 1024 or unit == "GiB":
            return f"{f:.1f} {unit}" if unit != "B" else f"{int(f)} B"
        f /= 1024
    return f"{n} B"


# --------------------------------------------------------------------------- #
# bash_script generation
# --------------------------------------------------------------------------- #
def render_unit(cfg: dict, service_name: str) -> str:
    svc = cfg.get("service", {})
    exec_start = cfg["exec_start"]
    restart = svc.get("restart", "always")
    restart_sec = svc.get("restart_sec", 2)
    env_file = svc.get("env_file", DEFAULT_ENV_FILE)
    after = svc.get("after", ["dstack-guest-agent.service"])
    extra = svc.get("extra", [])

    unit_lines = [
        "[Unit]",
        f"Description={cfg['name']} (dstack self-contained app)",
    ]
    if after:
        unit_lines.append(f"After={' '.join(after)}")
    unit_lines += [
        "",
        "[Service]",
        f"ExecStart={exec_start}",
        f"Restart={restart}",
        f"RestartSec={restart_sec}",
    ]
    if env_file:
        # leading '-' => optional (don't fail if the file is absent)
        unit_lines.append(f"EnvironmentFile=-{env_file}")
    for line in extra:
        unit_lines.append(str(line))
    unit_lines += [
        "",
        "[Install]",
        "WantedBy=multi-user.target",
    ]
    return "\n".join(unit_lines) + "\n"


def render_bash_script(cfg: dict, files: list[dict], service_name: str) -> str:
    runtime_dir = cfg["runtime_dir"]
    unit = render_unit(cfg, service_name)

    decode_calls = "\n".join(
        f'decode_payload {json.dumps(f["dest"])} {json.dumps(f["mode"])}'
        for f in files
    )

    # NOTE: this script runs via `jq -r '.bash_script' app-compose.json | bash`
    # from /dstack (app-compose.sh). cwd is /dstack; app-compose.json is here.
    return f"""# generated by sca — do not edit by hand
set -euo pipefail

COMPOSE_FILE=app-compose.json
RUNTIME_DIR={json.dumps(runtime_dir)}
UNIT_NAME={json.dumps(service_name + ".service")}

note() {{ dstack-util notify-host -e boot.progress -d "$1" || true; }}

note "sca: decoding payloads"
mkdir -p "$RUNTIME_DIR"

# the guest has no `base64`; openssl decodes binary safely.
decode_payload() {{
    local rel="$1" mode="$2"
    local out="$RUNTIME_DIR/$rel"
    mkdir -p "$(dirname "$out")"
    jq -r --arg k "$rel" '.sca_payloads[$k]' "$COMPOSE_FILE" \\
        | openssl base64 -d -A > "$out"
    chmod "$mode" "$out"
}}

{decode_calls}

note "sca: installing systemd unit"
# write the unit to /run (tmpfs, writable, ephemeral); systemd reads it there.
mkdir -p /run/systemd/system
cat > "/run/systemd/system/$UNIT_NAME" <<'__SCA_UNIT__'
{unit}__SCA_UNIT__

systemctl daemon-reload
note "sca: starting $UNIT_NAME"
# `start` returns immediately so the oneshot app-compose.service completes and
# boot is marked done; systemd then supervises the app (Restart=always).
systemctl start "$UNIT_NAME"
note "sca: started"
"""


# --------------------------------------------------------------------------- #
# build
# --------------------------------------------------------------------------- #
def normalize_files(cfg: dict, base_dir: Path) -> list[dict]:
    raw = cfg.get("files")
    if not raw:
        die("config has no [[files]] entries; at least the app binary is required")
    files = []
    seen = set()
    for i, entry in enumerate(raw):
        src = entry.get("src")
        if not src:
            die(f"[[files]] #{i} is missing 'src'")
        dest = entry.get("dest") or Path(src).name
        mode = str(entry.get("mode", "0644"))
        if dest in seen:
            die(f"duplicate dest '{dest}' in [[files]]")
        seen.add(dest)
        path = (base_dir / src).resolve()
        if not path.is_file():
            die(f"payload file not found: {path}")
        files.append({"src": str(path), "dest": dest, "mode": mode})
    return files


def build_app_compose(cfg: dict, files: list[dict], service_name: str) -> dict:
    compose = cfg.get("compose", {})
    out: dict = {
        "manifest_version": cfg.get("manifest_version", 2),
        "name": cfg["name"],
        "runner": "bash",
    }
    # pass-through compose flags (only emit when present to keep hash minimal)
    flag_defaults = {
        "kms_enabled": False,
        "gateway_enabled": False,
        "local_key_provider_enabled": False,
        "public_logs": True,
        "public_sysinfo": True,
        "no_instance_id": False,
        "secure_time": False,
    }
    for key, default in flag_defaults.items():
        out[key] = bool(compose.get(key, default))
    out["key_provider_id"] = compose.get("key_provider_id", "")
    out["allowed_envs"] = list(compose.get("allowed_envs", []))
    if compose.get("key_provider"):
        out["key_provider"] = compose["key_provider"]
    if compose.get("swap_size_mb"):
        out["swap_size"] = int(compose["swap_size_mb"]) * 1024 * 1024

    out["bash_script"] = render_bash_script(cfg, files, service_name)

    payloads: dict = {}
    for f in files:
        data = Path(f["src"]).read_bytes()
        # standard base64 (RFC 4648); decodes cleanly with `openssl base64 -d`.
        payloads[f["dest"]] = base64.b64encode(data).decode("ascii")
    out["sca_payloads"] = payloads
    return out


def cmd_build(args) -> None:
    cfg_path = Path(args.config).resolve()
    if not cfg_path.is_file():
        die(f"config not found: {cfg_path} (run `sca new <dir>` first)")
    with open(cfg_path, "rb") as fh:
        cfg = tomllib.load(fh)

    for required in ("name", "runtime_dir", "exec_start"):
        if not cfg.get(required):
            die(f"config is missing required key '{required}'")

    base_dir = cfg_path.parent
    files = normalize_files(cfg, base_dir)
    service_name = slugify(cfg.get("service", {}).get("name") or cfg["name"])

    app_compose = build_app_compose(cfg, files, service_name)
    blob = json.dumps(app_compose, indent=2, ensure_ascii=False).encode("utf-8")

    out_path = Path(args.output).resolve()
    out_path.write_bytes(blob)

    digest = hashlib.sha256(blob).hexdigest()
    size = len(blob)

    print(f"wrote {out_path}")
    print(f"  service     : {service_name}.service  ->  {cfg['exec_start']}")
    print(f"  payloads    : {len(files)} file(s)")
    for f in files:
        raw = Path(f["src"]).stat().st_size
        print(f"      - {f['dest']} ({f['mode']}, {human(raw)} raw)")
    print(f"  size        : {human(size)} / {human(APP_COMPOSE_MAX_BYTES)} cap"
          f"  ({100 * size / APP_COMPOSE_MAX_BYTES:.1f}%)")
    print(f"  compose-hash: {digest}")
    print(f"  app-id      : {digest[:40]}")
    if size > APP_COMPOSE_MAX_BYTES:
        die(f"app-compose.json exceeds the {human(APP_COMPOSE_MAX_BYTES)} guest "
            "copy limit; shrink the binary or split the payload")
    if size > APP_COMPOSE_MAX_BYTES * 0.9:
        print("  warning: within 10% of the size cap", file=sys.stderr)
    print()
    print("next: deploy with vmm-cli, e.g.")
    print(f"  ./vmm-cli.py deploy --name {service_name} --image <os-image> \\")
    print(f"      --compose {out_path.name} --vcpu 1 --memory 1024 --disk 10")


# --------------------------------------------------------------------------- #
# new
# --------------------------------------------------------------------------- #
SCA_TOML_TEMPLATE = """# sca.toml — self-contained dstack app (no docker, no registry pull)

name = "{name}"
manifest_version = 2

# directory inside the CVM where embedded files are extracted at boot.
# must be tmpfs + exec: /run/* , /tmp , /dev/shm are all fine. /run is best
# for a long-running daemon. it is ephemeral and recreated on every boot.
runtime_dir = "/run/{slug}"

# the command systemd runs. use absolute paths under runtime_dir.
exec_start = "/run/{slug}/app"

# files embedded into app-compose.json (base64) and extracted at boot.
# the first one is usually your prebuilt binary. paths are relative to this file.
[[files]]
src = "dist/app"
dest = "app"
mode = "0755"

# [[files]]
# src = "dist/config.toml"
# dest = "config.toml"
# mode = "0644"

[service]
# name = "{slug}"              # systemd unit name (defaults to a slug of `name`)
restart = "always"
restart_sec = 2
# decrypted env from KMS (only populated when kms_enabled + allowed_envs). the
# leading '-' in the unit makes it optional, so this is safe to leave as-is.
env_file = "/dstack/.host-shared/.decrypted-env"
# after = ["dstack-guest-agent.service"]
# extra = ["WorkingDirectory=/run/{slug}"]   # raw extra [Service] lines

[compose]
kms_enabled = false
gateway_enabled = false
local_key_provider_enabled = false
public_logs = true
public_sysinfo = true
secure_time = false
no_instance_id = false
allowed_envs = []
# key_provider_id = ""
# swap_size_mb = 0
"""

README_TEMPLATE = """# {name}

self-contained dstack app: the binary is embedded in `app-compose.json` and run
under systemd inside the CVM — no docker, no registry pull.

## layout

- `sca.toml`   — build config (edit this)
- `dist/`      — put your prebuilt binary here (referenced by `[[files]].src`)

## build

    sca build                 # reads sca.toml, writes app-compose.json

prints the compose-hash and app-id. add the compose-hash to your on-chain
DstackApp whitelist before deploying.

## deploy

    ./vmm-cli.py deploy --name {slug} --image <os-image> \\
        --compose app-compose.json --vcpu 1 --memory 1024 --disk 10

## notes

- the binary is measured into RTMR3 via the compose-hash, so the exact bytes are
  attested. rebuilding the binary changes the compose-hash (re-whitelist).
- size cap: app-compose.json must stay under 50 MiB; base64 adds ~33%, so the
  practical binary budget is ~37 MB.
- the app runs as a systemd service with Restart=always. it can reach the
  guest-agent socket at /var/run/dstack.sock — don't add heavy unit sandboxing
  that would hide it.
"""


def cmd_new(args) -> None:
    target = Path(args.dir).resolve()
    name = args.name or target.name
    slug = slugify(name)

    if target.exists() and any(target.iterdir()):
        die(f"directory '{target}' exists and is not empty")
    (target / "dist").mkdir(parents=True, exist_ok=True)

    (target / "sca.toml").write_text(
        SCA_TOML_TEMPLATE.format(name=name, slug=slug)
    )
    (target / "README.md").write_text(
        README_TEMPLATE.format(name=name, slug=slug)
    )
    (target / "dist" / ".gitkeep").write_text("")

    print(f"scaffolded self-contained app '{name}' at {target}")
    print("  sca.toml      — edit build config")
    print("  dist/         — drop your prebuilt binary here (as dist/app)")
    print("  README.md     — notes")
    print()
    print("next:")
    print(f"  cp <your-binary> {target}/dist/app")
    print(f"  cd {target} && sca build")


# --------------------------------------------------------------------------- #
# cli
# --------------------------------------------------------------------------- #
def main(argv=None) -> None:
    parser = argparse.ArgumentParser(
        prog="sca",
        description="build self-contained dstack apps (no docker, no registry)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_new = sub.add_parser("new", help="scaffold a new self-contained app project")
    p_new.add_argument("dir", help="target directory to create")
    p_new.add_argument("--name", help="app name (defaults to directory name)")
    p_new.set_defaults(func=cmd_new)

    p_build = sub.add_parser("build", help="build app-compose.json from sca.toml")
    p_build.add_argument(
        "-c", "--config", default="sca.toml", help="path to sca.toml (default: ./sca.toml)"
    )
    p_build.add_argument(
        "-o", "--output", default="app-compose.json",
        help="output path (default: ./app-compose.json)",
    )
    p_build.set_defaults(func=cmd_build)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
