# SPDX-FileCopyrightText: © 2024-2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

workers = 8
max_blocking = 64
ident = "dstack Gateway"
temp_dir = "/tmp"
keep_alive = 10
log_level = "info"
port = 8010

[core]
kms_url = ""
state_path = "./gateway-state.json"
# auto set soft ulimit to hard ulimit
set_ulimit = true
rpc_domain = ""
run_in_dstack = true

[core.auth]
enabled = false
url = "http://localhost/app-auth"
timeout = "5s"

[core.admin]
enabled = false
port = 8011

[core.certbot]
enabled = false
workdir = "/etc/certbot"
acme_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
cf_api_token = ""
cf_zone_id = ""
auto_set_caa = true
domain = "*.example.com"
renew_interval = "1h"
renew_before_expiration = "10d"
renew_timeout = "120s"

[core.wg]
public_key = ""
private_key = ""
listen_port = 51820
ip = "10.0.0.1/24"
reserved_net = ["10.0.0.1/32"]
client_ip_range = "10.0.0.0/25"
config_path = "/etc/wireguard/wg0.conf"
interface = "wg0"
endpoint = "10.0.2.2:51820"

[core.proxy]
cert_chain = "/etc/rproxy/certs/cert.pem"
cert_key = "/etc/rproxy/certs/key.pem"
tls_crypto_provider = "aws-lc-rs"
tls_versions = ["1.2"]
base_domain = "app.localhost"
listen_addr = "0.0.0.0"
listen_port = 8443
agent_port = 8090
buffer_size = 8192
# number of hosts to try to connect to
connect_top_n = 3
localhost_enabled = false
app_address_ns_prefix = "_dstack-app-address"
app_address_ns_compat = true
workers = 32
external_port = 443

# PROXY Protocol configuration
[core.proxy.proxy_protocol]
enabled = true

[core.proxy.proxy_protocol.trust_strategy]
type = "all"  # Trust all sources by default (can be restricted to "ips", "cidrs", or "none")
# addresses = ["10.0.0.1", "10.0.0.2"]  # Optional: specific IPs when type = "ips"
# ranges = ["10.0.0.0/8", "172.16.0.0/12"]  # Optional: CIDR ranges when type = "cidrs"

[core.proxy.proxy_protocol.backend_default]
mode = "passthrough"  # Default: forward if received, don't add if not received
# version = "v2"  # Optional: specify v1 or v2, defaults to v2 when mode = "always"

# Optional: Override settings for specific backends
# [core.proxy.proxy_protocol.backend_overrides]
# "app1" = { mode = "never" }  # Never send PROXY Protocol to this app
# "app2" = { mode = "always", version = "v1" }  # Always send v1 PROXY Protocol

[core.proxy.timeouts]
# Timeout for establishing a connection to the target app.
connect = "5s"
# TLS-termination handshake timeout or SNI extraction timeout.
handshake = "5s"

# Timeout for top n hosts selection
cache_top_n = "30s"

# Enable data transfer timeouts below. This might impact performance. Turn off if
# bad performance is observed.
data_timeout_enabled = true
# Timeout for a connection without any data transfer.
idle = "10m"
# Timeout for writing data to the target app or to the client.
write = "5s"
# Timeout for shutting down a connection.
shutdown = "5s"
# Timeout for total connection duration.
total = "5h"

[core.recycle]
enabled = true
interval = "5m"
timeout = "10h"
node_timeout = "10m"

[core.sync]
enabled = false
interval = "30s"
broadcast_interval = "10m"
timeout = "2s"
my_url = "https://localhost:8011"
# The url of the bootnode used to join the network
bootnode = "https://localhost:8011"
