# SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
# SPDX-FileCopyrightText: © 2025 Test in Prod <contact@testinprod.io>
#
# SPDX-License-Identifier: Apache-2.0

services:
  auth-api:
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-bookworm-slim@sha256:2cf067cfed83d5ea958367df9f966191a942351a2df77d6f0193e162b5febfc0
        WORKDIR /app

        RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*
        RUN git clone ${GIT_REPOSITORY} && \
            cd dstack && \
            git checkout ${GIT_REV}
        WORKDIR /app/dstack/dstack/kms/auth-eth
        RUN npm ci
        RUN npm run build
        CMD node dist/main.js
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ETH_RPC_URL=${ETH_RPC_URL}
      - KMS_CONTRACT_ADDR=${KMS_CONTRACT_ADDR}
    restart: unless-stopped
    ports:
      - 8001:8000

  kms:
    image: ${KMS_IMAGE}
    volumes:
      - kms-volume:/kms
      - /var/run/dstack.sock:/var/run/dstack.sock
    ports:
      - 8000:8000
    depends_on:
      - auth-api
    restart: unless-stopped
    configs:
      - source: kms_config
        target: /kms/kms.toml
    command: sh -c 'mkdir -p /kms/certs /kms/images && exec dstack-kms -c /kms/kms.toml'

volumes:
  kms-volume:

configs:
  kms_config:
    content: |
      [rpc]
      address = "0.0.0.0"
      port = 8000

      [rpc.tls]
      key = "/kms/certs/rpc.key"
      certs = "/kms/certs/rpc.crt"

      [core]
      cert_dir = "/kms/certs"

      [core.image]
      verify = true
      cache_dir = "/kms/images"
      download_url = "${IMAGE_DOWNLOAD_URL}"
      download_timeout = "2m"

      [core.auth_api]
      type = "webhook"

      [core.auth_api.webhook]
      url = "http://auth-api:8000"

      [core.onboard]
      enabled = true
      auto_bootstrap_domain = ""
      address = "0.0.0.0"
      port = 8000
