// SPDX-FileCopyrightText: © 2026 Phala Network <dstack@phala.network>
//
// SPDX-License-Identifier: Apache-2.0

//! swtpm-backed GCP vTPM environment, including the pre-provisioned AK
//! template and certificate NV indices consumed by `tpm-attest`.

use std::{path::Path, process::Command, thread, time::Duration};

use anyhow::{bail, Context, Result};
use dstack_types::TeeSimulatorConfig;
use mock_attestation::{parse_seed, server::MockCollateralState};

const AK_ECC_CERT: &str = "0x01c10002";
const AK_ECC_TEMPLATE: &str = "0x01c10003";

fn command(program: &str, args: &[&str]) -> Result<()> {
    let status = Command::new(program)
        .args(args)
        .env("TPM2TOOLS_TCTI", "device:/dev/tpm0")
        .status()
        .with_context(|| format!("failed to execute {program}"))?;
    if !status.success() {
        bail!("{program} failed with status {status}");
    }
    Ok(())
}

pub fn start_gcp_vtpm(runtime_dir: &Path, config: &TeeSimulatorConfig) -> Result<()> {
    if Path::new("/dev/tpmrm0").exists() || Path::new("/dev/tpm0").exists() {
        bail!("refusing to start the GCP vTPM simulator when a real TPM is present");
    }
    let seed = config
        .mock_attestation_seed
        .as_deref()
        .context("tee_simulator.mock_attestation_seed is required")?;
    let base_url = config
        .collateral_base_url
        .as_deref()
        .unwrap_or("http://127.0.0.1:8088");
    let state = MockCollateralState::from_seed(parse_seed(seed)?, base_url)?;
    // Keep swtpm state outside /run: swtpm drops privileges to `tss`, and some
    // distributions reject its lock file when a parent runtime directory is
    // owned by root even if the immediate state directory is writable.
    let state_dir = std::env::temp_dir().join(format!("dstack-swtpm-{}", std::process::id()));
    fs_err::create_dir_all(&state_dir)?;
    let state_arg = format!("dir={}", state_dir.display());
    let pid_file = std::env::temp_dir().join(format!("dstack-swtpm-{}.pid", std::process::id()));
    let pid_arg = format!("file={}", pid_file.display());
    command(
        "swtpm",
        &[
            "chardev",
            "--tpm2",
            "--tpmstate",
            &state_arg,
            "--vtpm-proxy",
            "--pid",
            &pid_arg,
            "--daemon",
        ],
    )?;
    fs_err::copy(&pid_file, runtime_dir.join("swtpm.pid"))?;

    for _ in 0..100 {
        create_tpm_device_node()?;
        if Path::new("/dev/tpmrm0").exists() || Path::new("/dev/tpm0").exists() {
            break;
        }
        thread::sleep(Duration::from_millis(20));
    }
    command("tpm2_startup", &["-c"])?;
    replay_fixture_event_log()?;

    let template_with_size = state_dir.join("ak.tpm2b-public");
    let generated_public = state_dir.join("ak.public");
    let template = state_dir.join("ak.template");
    let public_pem = state_dir.join("ak.pem");
    let context = state_dir.join("ak.ctx");
    command(
        "tpm2_createprimary",
        &[
            "-C",
            "e",
            "-G",
            "ecc256:ecdsa-sha256:null",
            "-g",
            "sha256",
            "-a",
            "fixedtpm|fixedparent|sensitivedataorigin|userwithauth|restricted|sign|noda",
            "-c",
            context.to_str().context("invalid AK context path")?,
            "-o",
            generated_public
                .to_str()
                .context("invalid generated AK public path")?,
            "--template-data",
            template_with_size
                .to_str()
                .context("invalid AK public path")?,
        ],
    )?;
    command(
        "tpm2_readpublic",
        &[
            "-c",
            context.to_str().context("invalid AK context path")?,
            "-f",
            "pem",
            "-o",
            public_pem.to_str().context("invalid AK PEM path")?,
        ],
    )?;
    let bytes = fs_err::read(&template_with_size)?;
    anyhow::ensure!(!bytes.is_empty(), "invalid TPMT_PUBLIC generated by swtpm");
    fs_err::write(&template, bytes)?;

    let root_cert = state_dir.join("root.pem");
    let root_key = state_dir.join("root-key.pem");
    let ak_cert = state_dir.join("ak-cert.pem");
    let extensions = state_dir.join("ak-cert.ext");
    fs_err::write(&root_cert, state.tpm.root_ca_pem())?;
    fs_err::write(&root_key, state.tpm.root_key_pem())?;
    fs_err::write(
        &extensions,
        format!(
            "basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nauthorityInfoAccess=caIssuers;URI:{base_url}/tpm/aia/root.pem\ncrlDistributionPoints=URI:{base_url}/tpm/crl/root.crl\n"
        ),
    )?;
    command(
        "openssl",
        &[
            "x509",
            "-new",
            "-force_pubkey",
            public_pem.to_str().context("invalid AK PEM path")?,
            "-CAkey",
            root_key.to_str().context("invalid root key path")?,
            "-CA",
            root_cert.to_str().context("invalid root cert path")?,
            "-CAcreateserial",
            "-days",
            "30",
            "-subj",
            "/CN=Mock GCP vTPM AK",
            "-extfile",
            extensions.to_str().context("invalid extension path")?,
            "-outform",
            "DER",
            "-out",
            ak_cert.to_str().context("invalid AK certificate path")?,
        ],
    )?;
    provision_nv(AK_ECC_TEMPLATE, &template)?;
    provision_nv(AK_ECC_CERT, &ak_cert)?;
    command("tpm2_flushcontext", &["-t"])?;
    Ok(())
}

fn replay_fixture_event_log() -> Result<()> {
    let bytes = include_bytes!("../../cc-eventlog/samples/tpm_eventlog.bin");
    let event_log = cc_eventlog::tpm::TpmEventLog::decode(&mut bytes.as_slice())?;
    for event in event_log.events {
        let extension = format!("{}:sha256={}", event.pcr_index, hex::encode(event.digest));
        command("tpm2_pcrextend", &[&extension])?;
    }
    Ok(())
}

fn create_tpm_device_node() -> Result<()> {
    if Path::new("/dev/tpm0").exists() {
        return Ok(());
    }
    let sys_dev = Path::new("/sys/class/tpm/tpm0/dev");
    if !sys_dev.exists() {
        return Ok(());
    }
    let device = fs_err::read_to_string(sys_dev)?;
    let (major, minor) = device
        .trim()
        .split_once(':')
        .context("invalid /sys/class/tpm/tpm0/dev")?;
    command("mknod", &["/dev/tpm0", "c", major, minor])
}

fn provision_nv(index: &str, contents: &Path) -> Result<()> {
    let size = fs_err::metadata(contents)?.len().to_string();
    command(
        "tpm2_nvdefine",
        &[index, "-C", "o", "-s", &size, "-a", "ownerread|ownerwrite"],
    )?;
    command(
        "tpm2_nvwrite",
        &[
            index,
            "-C",
            "o",
            "-i",
            contents.to_str().context("invalid NV input path")?,
        ],
    )
}
