/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAppTcbPolicy,
  IAppTcbPolicyInterface,
} from "../../contracts/IAppTcbPolicy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "policy",
        type: "string",
      },
    ],
    name: "TcbPolicySet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "policy",
        type: "string",
      },
    ],
    name: "setTcbPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tcbPolicy",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAppTcbPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IAppTcbPolicyInterface {
    return new Interface(_abi) as IAppTcbPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAppTcbPolicy {
    return new Contract(address, _abi, runner) as unknown as IAppTcbPolicy;
  }
}
