/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IAppTcbPolicyInterface extends Interface {
  getFunction(
    nameOrSignature: "setTcbPolicy" | "supportsInterface" | "tcbPolicy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TcbPolicySet"): EventFragment;

  encodeFunctionData(
    functionFragment: "setTcbPolicy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tcbPolicy", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "setTcbPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tcbPolicy", data: BytesLike): Result;
}

export namespace TcbPolicySetEvent {
  export type InputTuple = [policy: string];
  export type OutputTuple = [policy: string];
  export interface OutputObject {
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAppTcbPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IAppTcbPolicy;
  waitForDeployment(): Promise<this>;

  interface: IAppTcbPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setTcbPolicy: TypedContractMethod<[policy: string], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tcbPolicy: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setTcbPolicy"
  ): TypedContractMethod<[policy: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tcbPolicy"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TcbPolicySet"
  ): TypedContractEvent<
    TcbPolicySetEvent.InputTuple,
    TcbPolicySetEvent.OutputTuple,
    TcbPolicySetEvent.OutputObject
  >;

  filters: {
    "TcbPolicySet(string)": TypedContractEvent<
      TcbPolicySetEvent.InputTuple,
      TcbPolicySetEvent.OutputTuple,
      TcbPolicySetEvent.OutputObject
    >;
    TcbPolicySet: TypedContractEvent<
      TcbPolicySetEvent.InputTuple,
      TcbPolicySetEvent.OutputTuple,
      TcbPolicySetEvent.OutputObject
    >;
  };
}
