# SPDX-FileCopyrightText: © 2026 Phala Network <dstack@phala.network>
# SPDX-License-Identifier: Apache-2.0

[default]
workers = 8
max_blocking = 64
ident = "dstack Gateway E2E Simulator"
temp_dir = "/tmp"
keep_alive = 10
log_level = "info"

[default.core]
keys_file = "/opt/dstack-simulator/appkeys.json"
compose_file = "/opt/dstack-simulator/app-compose.json"
sys_config_file = "/opt/dstack-simulator/sys-config.json"
data_disks = ["/"]

[default.core.simulator]
attestation_file = "/opt/dstack-simulator/attestation.bin"
patch_report_data = true

[internal]
address = "unix:/var/run/dstack/dstack.sock"
reuse = true
