name: Rust checks

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.86
      with:
        components: clippy

    - name: Run Clippy
      run: cargo clippy -- -D warnings --allow unused_variables

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.86
      with:
        components: rustfmt

    - name: Cargo fmt check
      run: cargo fmt --check --all

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.86

    - name: Run tests
      run: ./run-tests.sh
