# SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

name: SPDX License Check

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  reuse-lint:
    runs-on: ${{ vars.CI_RUNNER || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
      with:
        args: lint
